name: Build Windows Executable with PyInstaller

# 触发工作流的事件
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # 允许手动触发
  workflow_dispatch:

jobs:
  build-windows:
    # 使用 Windows 运行环境
    runs-on: windows-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.8' # 保持用户指定的 Python 版本
          architecture: 'x64'

      # 验证 mitm.py 存在
      - name: Check if mitm.py exists
        run: |
          if (Test-Path mitm.py) { Write-Output "mitm.py found" }
          else { Write-Output "mitm.py not found"; exit 1 }
        shell: pwsh

      # 安装依赖和 PyInstaller
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          pip install pyinstaller
        shell: pwsh

      # 运行 PyInstaller 打包
      - name: Build executable
        run: |
          pyinstaller -D -w mitm.py
        shell: pwsh
        # 说明：
        # -D: 打包为目录，生成 dist/mitm/ 包含 .exe 和依赖
        # -w: 无控制台窗口（适用于 GUI 程序）
        # --log-level DEBUG: 输出详细日志以便调试
        # 可根据需要添加其他参数，例如：
        # --icon=icon.ico（指定图标）
        # --add-data="path/to/resource;dest/path"（添加资源文件）

      # 调试：列出 dist/ 目录内容
      - name: List dist directory
        run: |
          Get-ChildItem -Path dist -Recurse
        shell: pwsh

      # 压缩 dist/mitm/ 为 mitm.zip
      - name: Create zip archive
        run: |
          Compress-Archive -Path dist/mitm/* -DestinationPath mitm.zip
        shell: pwsh

      # 上传打包结果
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable-zip
          path: mitm.zip
          retention-days: 7
