name: Build Windows Executable with PyInstaller

# 触发工作流的事件
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # 允许手动触发
  workflow_dispatch:

jobs:
  build-windows:
    # 使用 Windows 运行环境
    runs-on: windows-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.8' # 可根据需要调整 Python 版本
          architecture: 'x64'

      # 安装依赖和 PyInstaller
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if exist requirements.txt (pip install -r requirements.txt)
          pip install pyinstaller

      # 运行 PyInstaller 打包
      - name: Build executable
        run: |
          pyinstaller -D -w mitm.py
        # 说明：
        # -F: 打包为单个 .exe 文件
        # -w: 无控制台窗口（适用于 GUI 程序）
        # main.py: 替换为你的主 Python 文件名
        # 可根据需要添加其他参数，例如：
        # --icon=icon.ico（指定图标）
        # --add-data="path/to/resource;dest/path"（添加资源文件）

      # 上传打包结果
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/*.exe
          retention-days: 7
